application: butterwell
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  static_files: index.html
  upload: index\.html

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /1st_column
  static_dir: 1st_column 

- url: /2nd_column
  static_dir: 2nd_column 

- url: /3rd_column
  static_dir: 3rd_column

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /humans\.txt
  static_files: humans.txt
  upload: humans\.txt

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  static_files: 404.html
  upload: 404\.html
